ae = "/app/models/vae/ae.safetensors"
apply_t5_attn_mask = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
clip_l = "/app/models/clip/clip_l.safetensors"
clip_skip = 2
discrete_flow_shift = 3.1582
dynamo_backend = "no"
enable_bucket = true
epoch = 10
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
highvram = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
logging_dir = "/app/logs"
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0.1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_train_epochs = 10
max_train_steps = 1000000
min_bucket_reso = 256
min_snr_gamma = 7
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 32
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_dim = 32
network_module = "networks.lora_flux"
noise_offset = 0.05
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "/app/outputs"
output_name = "qili"
pretrained_model_name_or_path = "/app/models/unet/flux1-dev.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "/app/outputs/sample/prompt.txt"
sample_sampler = "euler"
save_every_n_epochs = 1
save_every_n_steps = 50
save_model_as = "safetensors"
save_precision = "bf16"
sdpa = true
seed = 42
t5xxl = "/app/models/clip/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = [ 0.0001, 0.0001,]
timestep_sampling = "shift"
train_batch_size = 2
train_data_dir = "/app/data/train/img"
unet_lr = 0.0001
wandb_run_name = "qili"
