pretrained_model_name_or_path = "/app/models/unet/flux1-dev-fp8.safetensors"
clip_l = "/app/models/clip/clip_l.safetensors"
t5xxl = "/app/models/clip/t5xxl_fp16.safetensors"
ae = "/app/models/vae/ae.safetensors"
train_data_dir = "/app/data/Flux-lora/电商-海报618"
logging_dir = "/app/logs"
output_dir = "/app/outputs/models"
output_name = "电商lora-海报618"
train_batch_size = 2
save_every_n_epochs = 50
optimizer_type = "PagedAdamW8bit"
optimizer_args = ["weight_decay=0.01","betas=0.9,0.95"]
learning_rate = 1e-4
text_encoder_lr = [ 1e-5, 1e-5,]
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0.001
bucket_no_upscale = true
network_dim = 24
network_alpha = 24
epoch = 100
max_train_epochs = 100
max_train_steps = 1000000000
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
clip_skip = 1
discrete_flow_shift = 3.1582
dynamo_backend = "no"
enable_bucket = true
gradient_accumulation_steps = 1
guidance_scale = 1.0
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
loss_type = "l2"
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_module = "networks.lora_flux"
noise_offset_type = "Original"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "/app/outputs/sample_prompt/prompt_电商海报618.txt"
sample_sampler = "euler_a"
sample_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
seed = 12345
t5xxl_max_token_length = 512
timestep_sampling = "shift"
xformers = false
fp8_base = false
fp8_base_unet = true
highvram = true
sdpa = true
gradient_checkpointing = true
